name: "Ibis Next Builds"
description: "Automatically build new eBook PDF files using Ibis Next"
author: "Bobby Iliev"
runs:
  using: "docker"
  image: "Dockerfile"
outputs:
  build:
    description: "Ibis Next build completed"
branding:
  icon: "git-merge"
  color: "purple"
