name: Ibis Next eBook Generation
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          fetch-depth: "0"
      - name: Build Ibis Next Export Files
        uses: bobbyiliev/ibis-build-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IBIS_PATH: "./ebook/en"
          IBIS_BRANCH: "main"
          EMAIL: "bobby@bobbyiliev.com"
          COMMIT_MESSAGE: "Updated Ibis Next Exported Files"
